// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMOGKJKYxv2V1e9FvTMY-2tGkXUFcryJI',
    appId: '1:851067278068:web:a6ef7f233109c4936284a1',
    messagingSenderId: '851067278068',
    projectId: 'serenityms-9023a',
    authDomain: 'serenityms-9023a.firebaseapp.com',
    storageBucket: 'serenityms-9023a.firebasestorage.app',
    measurementId: 'G-V5B1XB94L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNqsGNcK0A8H3Mmk5pB5ZHcRm_g2dkbKk',
    appId: '1:851067278068:android:183c8ec04c49af496284a1',
    messagingSenderId: '851067278068',
    projectId: 'serenityms-9023a',
    storageBucket: 'serenityms-9023a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMOGKJKYxv2V1e9FvTMY-2tGkXUFcryJI',
    appId: '1:851067278068:web:384b3cb2bc7ef6836284a1',
    messagingSenderId: '851067278068',
    projectId: 'serenityms-9023a',
    authDomain: 'serenityms-9023a.firebaseapp.com',
    storageBucket: 'serenityms-9023a.firebasestorage.app',
    measurementId: 'G-ZRVTE1EFV3',
  );

}